# Generated by Django 3.0.4 on 2020-03-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '学科', 'verbose_name_plural': '\uffff\uffff学科'},
        ),
    ]
