# Generated by Django 3.0.4 on 2020-03-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20200324_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '学科', 'verbose_name_plural': '学科'},
        ),
    ]
