# Generated by Django 3.0.4 on 2020-03-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20200324_2108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='db_teacherhaha\uffff',
        ),
    ]
