# Generated by Django 3.0.4 on 2020-03-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20200325_1404'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='db_subject',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='db_teacher',
        ),
    ]
