# Generated by Django 3.0.4 on 2020-03-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20200325_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='creat_date',
            field=models.DateField(null=True, verbose_name='成立日期'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='no',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
