# Generated by Django 3.0.4 on 2020-03-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(default='', max_length=11, verbose_name='手机号'),
        ),
    ]
